added a new api for uploading the files into the local project directory
ImbueNetwork/dapp pull request #110
Opened 2023-03-23 11:49 UTC by mshankarrao

2023-03-23 13:21 UTC, samelamin commented
Lets get this integrated on a page before merging please

Either on the edit brief page or the new brief form

But I want the files to be downloadable once someone explores the brief

2023-04-13 02:28 UTC, cuteolaf requested changes

2023-04-13 02:28 UTC, cuteolaf commented on api/src/frontend/tests/freelancers.test.tsx
> +        "web3_address": "test",
"web3_address" is duplicated.

2023-04-13 02:28 UTC, cuteolaf commented on api/src/frontend/tests/freelancers.test.tsx
> +        "web3_address": "test",
"web3_address" is duplicated.

2023-04-13 05:45 UTC, mshankarrao commented on api/src/frontend/tests/freelancers.test.tsx
> +        "web3_address": "test",
Hey isn’t the user is configured that way in the models file
 export type User = {
    id: number;
    display_name: string;
    web3Accounts: Web3Account[];
    username: string;
    password?: string;
    getstream_token: string;
    web3_address: string;
};

2023-04-13 08:25 UTC, cuteolaf commented on api/src/frontend/tests/freelancers.test.tsx
> +        "web3_address": "test",
yeah,but in test code, it has two "web3_address" member in one object.
That's why I mentioned about it.

2023-04-13 09:00 UTC, mshankarrao commented on api/src/frontend/tests/freelancers.test.tsx
> +        "web3_address": "test",
Ah got it thanks for pointing out

2023-04-13 10:19 UTC, mshankarrao commented on api/src/frontend/tests/freelancers.test.tsx
> +        "web3_address": "test",
Got it and fixed it

2023-04-13 12:39 UTC, merged