running on virtualbox
ImbueNetwork/dapp pull request #78
Opened 2023-02-07 17:19 UTC by simrat12

Brief explanation of how to run this repo using Virtualbox with an Ubuntu ISO file.

2023-02-08 09:23 UTC, samelamin commented
Thanks for this @simrat12 , can you merge/rebase master into this to resolve conflicts?

2023-02-13 16:41 UTC, f-gate requested changes
see comment

2023-02-13 16:41 UTC, f-gate commented on README.md
> -1. Add some env variables to your bash profile and source.
Hold on... This is removing the unix/docker instructions?

Can we keep those please!! haha.

2023-02-14 12:47 UTC, f-gate approved these changes
thanks!

2023-02-14 12:56 UTC, merged

2023-02-14 12:56 UTC, samelamin commented
thanks @simrat12